version: "3.8"

services:
  # ğŸ˜ PostgreSQL Servisi
  postgres:
    image: postgres:15-alpine
    container_name: ticketing_postgres
    ports:
      - "5433:5432" # DÄ±ÅŸarÄ±dan 5433, iÃ§eriden 5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticketing-network

  # âš¡ Redis Servisi
  redis:
    image: redis:alpine
    container_name: ticketing_redis
    ports:
      - "6379:6379"
    # AOF (Append Only File) aÃ§alÄ±m ki restart edince veriler uÃ§masÄ±n (opsiyonel ama hardcore iÃ§in iyi)
    command: redis-server --appendonly yes 
    networks:
      - ticketing-network

  # ğŸ—„ï¸ SQL GUI
  adminer:
    image: adminer
    container_name: ticketing_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - ticketing-network

  # ğŸ•µï¸ Redis GUI 
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ticketing_redis_gui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - ticketing-network
    depends_on:
      - redis

volumes:
  postgres_data:

networks:
  ticketing-network:
    driver: bridge